version: "3.2"

services:
  tag_library_dev:
    container_name: tag-lib-dev
    image: adamsandersonaccess/tag-library-dev:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
        - "3366:3366"
  demo_app_dev:
    container_name: demo_app_dev
    image: adamsandersonaccess/tag-library-demo-app:latest
    command: npm start
    working_dir: /app
    volumes:
      - ./src:/app/tag-library/src
    ports:
      - "3333:3333"
      - "35729:35729"

